version: '3.8'

services:
  ai-travel-planner:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped