# Railway Nixpacks 配置
[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo '確保前端文件存在'",
  "ls -la frontend/",
  "echo '構建完成'"
]

[start]
cmd = "python backend/app.py"
workingDirectory = "/app"
workingDirectory = "/app"